/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AppBacklogRouteImport } from './routes/_app.backlog'
import { Route as AppDoneRouteImport } from './routes/_app.done'
import { Route as AppLaterRouteImport } from './routes/_app.later'
import { Route as AppTodayRouteImport } from './routes/_app.today'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBacklogRoute = AppBacklogRouteImport.update({
  id: '/backlog',
  path: '/backlog',
  getParentRoute: () => AppRoute,
} as any)
const AppDoneRoute = AppDoneRouteImport.update({
  id: '/done',
  path: '/done',
  getParentRoute: () => AppRoute,
} as any)
const AppLaterRoute = AppLaterRouteImport.update({
  id: '/later',
  path: '/later',
  getParentRoute: () => AppRoute,
} as any)
const AppTodayRoute = AppTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/backlog': typeof AppBacklogRoute
  '/done': typeof AppDoneRoute
  '/later': typeof AppLaterRoute
  '/today': typeof AppTodayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/backlog': typeof AppBacklogRoute
  '/done': typeof AppDoneRoute
  '/later': typeof AppLaterRoute
  '/today': typeof AppTodayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_app/backlog': typeof AppBacklogRoute
  '/_app/done': typeof AppDoneRoute
  '/_app/later': typeof AppLaterRoute
  '/_app/today': typeof AppTodayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sign-in' | '/backlog' | '/done' | '/later' | '/today'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sign-in' | '/backlog' | '/done' | '/later' | '/today'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/sign-in'
    | '/_app/backlog'
    | '/_app/done'
    | '/_app/later'
    | '/_app/today'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/backlog': {
      id: '/_app/backlog'
      path: '/backlog'
      fullPath: '/backlog'
      preLoaderRoute: typeof AppBacklogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/done': {
      id: '/_app/done'
      path: '/done'
      fullPath: '/done'
      preLoaderRoute: typeof AppDoneRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/later': {
      id: '/_app/later'
      path: '/later'
      fullPath: '/later'
      preLoaderRoute: typeof AppLaterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/today': {
      id: '/_app/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AppTodayRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBacklogRoute: typeof AppBacklogRoute
  AppDoneRoute: typeof AppDoneRoute
  AppLaterRoute: typeof AppLaterRoute
  AppTodayRoute: typeof AppTodayRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBacklogRoute: AppBacklogRoute,
  AppDoneRoute: AppDoneRoute,
  AppLaterRoute: AppLaterRoute,
  AppTodayRoute: AppTodayRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
